In [1]:
import numpy as np

In [2]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


In [3]:
A_system = np.hstack((A, b.reshape((3, 1))))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [4]:
# exchange row_num of the matrix M with its multiple by row_num_multiple
# Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
def multiplyRows(Matrix , row_num , multiple):
    if multiple == 0:
        return "Not Valid. Enter a non-zero value"
    M_new = Matrix.copy()
    M_new[row_num] = multiple * M_new[row_num]
    return M_new
print(f"Original Matrix : \n {A_system}")
print(f"After Multiplying row 2 with 2: \n {multiplyRows(A_system,1,2)}")

Original Matrix : 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
After Multiplying row 2 with 2: 
 [[  4.  -3.   1. -10.]
 [  4.   2.   6.   0.]
 [ -1.   2.  -5.  17.]]


In [5]:
# multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
# exchanging row_num_2 of the matrix M in the result
def addRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    # M_new[[row_num_2]] = row_num_1_multiple * M_new[[row_num_1]] + M_new[[row_num_2]]
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(addRows(A_system,1,2,1/2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [6]:
# exchange row_num_1 and row_num_2 of the matrix M
def swapRows(Matrix,row_num_1,row_num_2):
    M_new = Matrix.copy()
    M_new[[row_num_2,row_num_1]] = M_new[[row_num_1,row_num_2]]
    return M_new

print(A_system)
print(swapRows(A_system,1,2))

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
[[  4.  -3.   1. -10.]
 [ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]]
