In [1]:
import numpy as np
import sys

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a = [1,2,3,4]
b = [5,6,7,8]

np_a = np.array(a)
np_b = np.array(b)

print(np_a,a)


[1 2 3 4] [1, 2, 3, 4]


In [3]:
#1D and 2D arrays
a = np.array([1,2,3,4],dtype='int32')
print(a)
b = np.array([[9.0, 8.0, 7.0],[4.0, 5.0, 6.0]])
print(b)

[1 2 3 4]
[[9. 8. 7.]
 [4. 5. 6.]]


In [4]:
#Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#Get Shape
a.shape
b.shape


(2, 3)

In [6]:
#Get Size
a.itemsize
# b.itemsize

4

In [7]:
a.nbytes

16

##### Row and Column operations

In [8]:
two_d_a = np.random.randint(15,size=(4,7))
print(two_d_a)

[[ 0 14  7 14  9  5  1]
 [ 0 14  9 12  8 14  7]
 [ 8  6 11  8  3  5  9]
 [ 1  5  6  2  5  2  2]]


In [9]:
#Get a specific element
two_d_a[1,5] #Mention [r,c] or [r][c]

14

In [12]:
two_d_a[0,:]
two_d_a[:,0]
print(two_d_a[0,1:-1:2])
print(two_d_a[1:,2])

[14 14  5]
[ 9 11  6]


In [13]:
two_d_a[1,5] = 27
two_d_a 

two_d_a[2,:] = 44
two_d_a

two_d_a[:,3] = 95
two_d_a[2,3] = 44 + 95
two_d_a

array([[  0,  14,   7,  95,   9,   5,   1],
       [  0,  14,   9,  95,   8,  27,   7],
       [ 44,  44,  44, 139,  44,  44,  44],
       [  1,   5,   6,  95,   5,   2,   2]])

In [14]:
#3D array
b = np.random.randint(20,size=(2,2,2))
b

array([[[ 5,  4],
        [19, 16]],

       [[10,  3],
        [11, 11]]])

In [17]:
#Get specific element
b[1,0,1] #2nd matrix  1st row 2nd col

3

In [19]:
b[1,:,:]
# b.dtype

array([[10,  3],
       [11, 11]])

In [20]:
#All 0's
np.zeros((2,3,4),dtype='int16')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [21]:
#all 1's 
np.ones((2,3,4),dtype='int16')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.full((1,3),104,dtype='int16')

array([[104, 104, 104]], dtype=int16)

In [23]:
np.full_like(two_d_a,24)


array([[24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24]])

In [26]:
# Random decimal numbers
np.random.rand(4,4)


array([[0.54758738, 0.39620586, 0.66135613, 0.45493648],
       [0.90343948, 0.37159658, 0.48343648, 0.00531914],
       [0.39517735, 0.55558335, 0.42482857, 0.29163882],
       [0.37216734, 0.74589758, 0.35165985, 0.06562714]])

In [27]:
#Integer Values
np.random.randint(-5,7,size=(2,3))

array([[-1, -4, -2],
       [ 5, -3, -4]])

In [28]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#repeat an array
c = np.array([[[1,2,3]]])
r1 = np.repeat(c,3,axis=0)
r1

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [36]:
a = np.ones((5,5))
# for i in range(1,4):
#     a[i,1:4] = 0
# a[2,2] = 9
print(a)

b = np.zeros((3,3))
b[1,1] = 9
print(b)

a[1:4,1:4] = b 
print(a)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying Arrays 

In [39]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 25 
b
a

array([1, 2, 3])


#### MAths ####

In [40]:
a = np.array([1,2,3,4])
print(a+2,a-2,a*2,a/2,a ** 2,np.sin(a),sep="\n")

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


##### Linear algebra

In [41]:
# matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2),7)
print(b)

# @ - np.matmul
print(a @ b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]
[[21. 21.]
 [21. 21.]]


In [42]:
#Detriminant of identity matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [52]:
#Loading from a file

arr = np.genfromtxt('/media/indraneel/YO/Programming/ML/datafiles/data.txt',delimiter=',')
arr.astype('int32')
# print(arr)

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)